[package]
name = "adder"
version = "0.1.0"
authors = ["Ricardo Havill <rhavill2002@yahoo.com>"]
edition = "2018"

[dependencies]
rand = "0.3.14"
add-one = { path = "../add-one" }
add-two = { path = "../add-two" }

